
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashirli
 */
public class Oyun extends javax.swing.JFrame {
    DefaultListModel model=new DefaultListModel();
int sozhaqqi=3;
int herfhaqqi=6;
Sozler sozler=new Sozler();
String secilen_soz;
String bitime_soz;
String oyuncu;
int sayac=1;
    /**
     * Creates new form Oyun
     */
    public Oyun() {
        initComponents();
        jList1.setModel(model);
    herf_haqq.setText("Herf haqq: "+herfhaqqi);
    soz_haqq.setText("Söz haqq: "+sozhaqqi);
    secilen_soz=sozler.secilen_soz;
      
    secilen_soz=secilen_soz.toUpperCase();
   
    if(secilen_soz.length()==4){
     bes.setVisible(false);
     alti.setVisible(false);
     yeddi.setVisible(false);
    }else if(secilen_soz.length()==5){
     alti.setVisible(false);
     yeddi.setVisible(false);
    }else if(secilen_soz.length()==6){
     yeddi.setVisible(false);
    }
  jLabel3.setText("Söz "+secilen_soz.length()+" herflidir.");
    
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField12 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        uc = new javax.swing.JTextField();
        dord = new javax.swing.JTextField();
        soz_haqq = new javax.swing.JLabel();
        soz_daxil = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        bes = new javax.swing.JTextField();
        yeddi = new javax.swing.JTextField();
        iki = new javax.swing.JTextField();
        bir = new javax.swing.JTextField();
        alti = new javax.swing.JTextField();
        herf_haqq = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        herf_daxil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField3 = new javax.swing.JTextField();

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        uc.setEditable(false);
        uc.setBackground(new java.awt.Color(0, 0, 0));
        uc.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        uc.setForeground(new java.awt.Color(255, 51, 0));

        dord.setEditable(false);
        dord.setBackground(new java.awt.Color(0, 0, 0));
        dord.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        dord.setForeground(new java.awt.Color(255, 51, 0));

        soz_haqq.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        soz_daxil.setText("Sözü daxil et");
        soz_daxil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soz_daxilActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        bes.setEditable(false);
        bes.setBackground(new java.awt.Color(0, 0, 0));
        bes.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        bes.setForeground(new java.awt.Color(255, 51, 0));

        yeddi.setEditable(false);
        yeddi.setBackground(new java.awt.Color(0, 0, 0));
        yeddi.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        yeddi.setForeground(new java.awt.Color(255, 51, 51));

        iki.setEditable(false);
        iki.setBackground(new java.awt.Color(0, 0, 0));
        iki.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        iki.setForeground(new java.awt.Color(255, 51, 0));

        bir.setEditable(false);
        bir.setBackground(new java.awt.Color(0, 0, 0));
        bir.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        bir.setForeground(new java.awt.Color(255, 51, 0));

        alti.setEditable(false);
        alti.setBackground(new java.awt.Color(0, 0, 0));
        alti.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        alti.setForeground(new java.awt.Color(255, 51, 51));

        herf_haqq.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        herf_daxil.setText("Herfi daxil et");
        herf_daxil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herf_daxilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Herf");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Söz");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(herf_haqq, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                                .addComponent(soz_haqq, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(dord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(alti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(yeddi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(herf_daxil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(soz_daxil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeddi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(herf_daxil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soz_daxil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(herf_haqq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soz_haqq, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jList1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField3.setText("Daxil edilenler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void herf_daxilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herf_daxilActionPerformed
        // TODO add your handling code here:

        if(herfhaqqi==0){
            JOptionPane.showMessageDialog(this, "Herf haqqiniz qalmadi.");
            jTextField1.setText("");
            return;
        }
        if(problem_tapma(jTextField1.getText().toString())==0){
            return;
        }
        for(int i=0;i<secilen_soz.length();i++){
            if(secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){

                if(i==0&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    bir.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==1&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    iki.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==2&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    uc.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==3&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    dord.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==4&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){

                    bes.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==5&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    alti.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
                if(i==6&&secilen_soz.charAt(i)==jTextField1.getText().toUpperCase().charAt(0)){
                    yeddi.setText(" "+jTextField1.getText().toString().toUpperCase());

                }
            }

        }
          String bild=sayac+". "+jTextField1.getText().toString();
        model.addElement(bild);
      sayac++;
        jTextField1.setText("");
        switch (secilen_soz.length()) {
            case 4:
            bitime_soz=bir.getText().toString().trim()+iki.getText().toString().trim()+uc.getText().toString().trim()+dord.getText().toString().trim();
            break;
            case 5:
            bitime_soz=bir.getText().toString().trim()+iki.getText().toString().trim()+uc.getText().toString().trim()+dord.getText().toString().trim()+bes.getText().toString().trim();
            break;
            case 6:
            bitime_soz=bir.getText().toString().trim()+iki.getText().toString().trim()+uc.getText().toString().trim()+dord.getText().toString().trim()+bes.getText().toString().trim()+alti.getText().toString().trim();
            break;
            case 7:
            bitime_soz=bir.getText().toString().trim()+iki.getText().toString().trim()+uc.getText().toString().trim()+dord.getText().toString().trim()+bes.getText().toString().trim()+alti.getText().toString().trim()+yeddi.getText().toString().trim();
            break;
        }

        if(bitime_soz.equals(secilen_soz)){
            JOptionPane.showMessageDialog(this, "Oyun bitdi. Tebrikler "+oyuncu+"! \n Oyunu qazandınız.");
            setVisible(false);
            //EKRAN
            GameOver go=new GameOver();
go.oyuncu=oyuncu;
go.setVisible(true);
            setVisible(false);
            return;
        }
     
        herfhaqqi--;
        herf_haqq.setText("Herf haqq: "+herfhaqqi);
          if(sozhaqqi==0&&herfhaqqi==0){
            JOptionPane.showMessageDialog(this, "Oyunu uduzdunuz. \n "+secilen_soz+" bu sözü tapa bilmediniz.");
            setVisible(false);
            //EKRAN
            GameOver go=new GameOver();
            go.oyuncu=oyuncu;
            go.setVisible(true);
            setVisible(false);
            return;
        }
    }//GEN-LAST:event_herf_daxilActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void soz_daxilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soz_daxilActionPerformed
        // TODO add your handling code here:
      
        if(sozhaqqi==0){
            JOptionPane.showMessageDialog(this, "Söz haqqiniz qalmadi.");
            jTextField2.setText("");
            return;
        }

        if(jTextField2.getText().toString().toUpperCase().equals(secilen_soz)){
            JOptionPane.showMessageDialog(this, "Oyun bitdi. Tebrikler "+oyuncu+"! \n Oyunu qazandınız.");
            setVisible(false);
            //EKRAN
            GameOver go=new GameOver();
            go.oyuncu=oyuncu;
            go.setVisible(true);
            setVisible(false);
            return;
        }else{
            JOptionPane.showMessageDialog(this, "Sehv tapdınız");
            sozhaqqi--;
            soz_haqq.setText("Soz haqq: "+sozhaqqi);
    model.addElement(sayac+". "+jTextField2.getText().toString());
      sayac++;
      jTextField2.setText("");
        } 
        if(sozhaqqi==0&&herfhaqqi==0){
            JOptionPane.showMessageDialog(this, "Oyunu uduzdunuz. \n "+secilen_soz+" bu sözü tapa bilmediniz.");
            setVisible(false);
            //EKRAN
            GameOver go=new GameOver();
            go.oyuncu=oyuncu;
            go.setVisible(true);
            setVisible(false);
            return;
        }
    }//GEN-LAST:event_soz_daxilActionPerformed

    int problem_tapma(String str){
        if(str.length()>1){
            JOptionPane.showMessageDialog(this,"Herf düzgün daxil edilmeyib.\n Haqqinizdan cixilmayacaq.");
            return 0;
        }
        if(str.length()==0){
        JOptionPane.showMessageDialog(this,"Herf daxil edilmeyib.\n Haqqinizdan cixilmayacaq.");
            return 0;    
        }
        return 1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oyun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alti;
    private javax.swing.JTextField bes;
    private javax.swing.JTextField bir;
    private javax.swing.JTextField dord;
    private javax.swing.JButton herf_daxil;
    private javax.swing.JLabel herf_haqq;
    private javax.swing.JTextField iki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton soz_daxil;
    private javax.swing.JLabel soz_haqq;
    private javax.swing.JTextField uc;
    private javax.swing.JTextField yeddi;
    // End of variables declaration//GEN-END:variables
}
